import static org.junit.Assert.*;

import org.junit.Before;
import org.junit.Test;


public class FacePamphletNotifications {
	private FacePamphletProfile profile;

	@Before
	public void setUp() throws Exception {
		profile = new FacePamphletProfile("Andy Derple");
	}
	/**
	 * Tests for the notification system.
	 * Covers receiving a notification, reproducing the notification,
	 * notifications generated by public/private messaging, 
	 * and notification clearing in two different ways.
	 * @author Cameron Ross
	 */
	@Test
	public void test() {
		profile.addNotification("User exploded");
		
		assertArrayEquals(profile.getNotifications().toArray(), new String[] { "User exploded" });
		
		profile.clearAllNotifications();
		assertEquals(profile.getNotifications().size(), 0);

		profile.publicMessage("Bees", "Cats");
		
		assertEquals(profile.getNotifications().size(), 1);
		profile.clearAllNotifications();
		
		profile.publicMessage("Bees Plus", "Cats Doubled");
		
		assertEquals(profile.getNotifications().size(), 1);
		
		profile.clearNotification(0);
		assertEquals(profile.getNotifications().size(), 0);
		try {
			profile.clearNotification(0);
			fail("Clearing nonexistant notification did not throw error");
		} catch (Exception e) {
			
		}
	}

}
