package FaceFront;

import Panels.ImagePanel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.util.Arrays;

import javax.swing.JOptionPane;
import javax.swing.event.MouseInputListener;

/* To change this template, choose Tools | Templates and open the template in the editor. */
/**
 *
 * @author John Maguire
 */
public class FacePamphlet extends javax.swing.JFrame {

    public enum BarType {

        FRIEND, OWN
    };

    /**
     * Creates new form FacePamphlet
     */
    public FacePamphlet() {
        this.initComponents();
        this.setToolBar(BarType.FRIEND);
    }

    public void setToolBar(BarType setTo) {
        ToolsInHere.removeAll();
        switch (setTo) {
            case FRIEND:

                AddPicture.setAlignmentX(Component.CENTER_ALIGNMENT);
                AddPost.setAlignmentX(Component.CENTER_ALIGNMENT);
                ChangeBack.setAlignmentX(Component.CENTER_ALIGNMENT);

                ToolsInHere.add(this.AddPicture);
                ToolsInHere.add(this.AddPost);
                ToolsInHere.add(this.ChangeBack);

                break;
            case OWN:
                break;


        }
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PamplhetCanvas = new javax.swing.JPanel();
        AddPicture = new javax.swing.JButton();
        ChangeBack = new javax.swing.JButton();
        AddPost = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Canvas = new PamphletCanvas();
        Testing = new javax.swing.JPanel();
        ToolsInHere = new javax.swing.JPanel();
        MenuBar = new javax.swing.JPanel(){

            public void paintComponent(Graphics g){
                super.paintComponent(g);
                for(Component j:MenuBar.getComponents()){
                    System.out.println(j);
                }
                System.out.println("\n\n");
            }
        };
        SearchField = new javax.swing.JTextField();
        SearchLabel = new javax.swing.JLabel();

        PamplhetCanvas.setBackground(new java.awt.Color(255, 255, 255));
        PamplhetCanvas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PamplhetCanvasFocusGained(evt);
            }
        });

        javax.swing.GroupLayout PamplhetCanvasLayout = new javax.swing.GroupLayout(PamplhetCanvas);
        PamplhetCanvas.setLayout(PamplhetCanvasLayout);
        PamplhetCanvasLayout.setHorizontalGroup(
            PamplhetCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PamplhetCanvasLayout.setVerticalGroup(
            PamplhetCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        AddPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImages/PlusPic.png"))); // NOI18N
        AddPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPictureActionPerformed(evt);
            }
        });

        ChangeBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImages/PlusBack.jpg"))); // NOI18N
        ChangeBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeBackActionPerformed(evt);
            }
        });

        AddPost.setText("AddPost");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FacePamphlet");
        setBackground(new java.awt.Color(255, 51, 102));
        setForeground(new java.awt.Color(204, 0, 204));
        setName("App Frame"); // NOI18N
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        Canvas.setBackground(new java.awt.Color(255, 255, 255));
        Canvas.setBorder(null);
        Canvas.setForeground(new java.awt.Color(255, 255, 255));
        Canvas.setToolTipText("");
        Canvas.setName("Canvas"); // NOI18N
        Canvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CanvasMousePressed(evt);
            }
        });
        Canvas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                CanvasMouseDragged(evt);
            }
        });
        Canvas.setLayout(null);

        Testing.setBackground(new java.awt.Color(255, 255, 0));
        Testing.setName("Gadget"); // NOI18N
        Testing.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                TestingComponentMoved(evt);
            }
        });

        javax.swing.GroupLayout TestingLayout = new javax.swing.GroupLayout(Testing);
        Testing.setLayout(TestingLayout);
        TestingLayout.setHorizontalGroup(
            TestingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        TestingLayout.setVerticalGroup(
            TestingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Canvas.add(Testing);
        Testing.setBounds(130, 40, 100, 100);

        ToolsInHere.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        ToolsInHere.setPreferredSize(new java.awt.Dimension(100, 0));
        ToolsInHere.setLayout(new javax.swing.BoxLayout(ToolsInHere, javax.swing.BoxLayout.PAGE_AXIS));

        MenuBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));

        SearchField.setForeground(java.awt.Color.lightGray);
        SearchField.setText("search for friends");
        SearchField.setName("SearchField"); // NOI18N
        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });
        SearchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchFieldFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchFieldFocusGained(evt);
            }
        });
        SearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SearchFieldKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchFieldKeyPressed(evt);
            }
        });

        SearchLabel.setText("Search:");
        SearchLabel.setName("SearchLabel"); // NOI18N

        javax.swing.GroupLayout MenuBarLayout = new javax.swing.GroupLayout(MenuBar);
        MenuBar.setLayout(MenuBarLayout);
        MenuBarLayout.setHorizontalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuBarLayout.createSequentialGroup()
                .addContainerGap(626, Short.MAX_VALUE)
                .addComponent(SearchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        MenuBarLayout.setVerticalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchLabel)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ToolsInHere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(MenuBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Canvas, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                    .addComponent(ToolsInHere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    }//GEN-LAST:event_formMouseClicked

    private void ChangeBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeBackActionPerformed

    private void AddPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPictureActionPerformed
        this.setVisible(false);
        
        new PictureSelect(this);
    }//GEN-LAST:event_AddPictureActionPerformed

    private void CanvasMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CanvasMouseDragged
        ((MouseMotionListener) Canvas).mouseDragged(evt);
    }//GEN-LAST:event_CanvasMouseDragged

    private void CanvasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CanvasMousePressed
        ((PamphletCanvas) Canvas).mousePressed(evt);
    }//GEN-LAST:event_CanvasMousePressed

    private void TestingComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TestingComponentMoved
    }//GEN-LAST:event_TestingComponentMoved

    private void SearchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchFieldKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER && !SearchField.getText().trim().equals("")) {
            // DO THE SEARCH

            JOptionPane.showMessageDialog(this, "Enter was pressed, would normally do search now", "To Implement",
                    JOptionPane.INFORMATION_MESSAGE);

        }    }//GEN-LAST:event_SearchFieldKeyPressed

    private void SearchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchFieldKeyTyped
        SearchFieldKeyPressed(evt);
    }//GEN-LAST:event_SearchFieldKeyTyped

    private void SearchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFieldFocusGained
        SearchField.setText("");
        SearchField.setForeground(Color.BLACK);    }//GEN-LAST:event_SearchFieldFocusGained

    private void SearchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFieldFocusLost
        if (SearchField.getText().trim().equals("")) {
            SearchField.setText("search for friends");
            SearchField.setForeground(Color.GRAY);
        }    }//GEN-LAST:event_SearchFieldFocusLost

    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchFieldActionPerformed

    private void PamplhetCanvasFocusGained(java.awt.event.FocusEvent evt) {
    }

    private void formMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_formMousePressed
    }// GEN-LAST:event_formMousePressed

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacePamphlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacePamphlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacePamphlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacePamphlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacePamphlet().setVisible(true);
            }
        });
    }

    public void addPicture(String title, BufferedImage toAdd) {
        ImagePanel y = new ImagePanel(title, toAdd);

        y.setBounds(this.getWidth() / 2 -100, this.getHeight() /2 -100, 200, 200);
        int[] toPrint = new int[]{y.getX(), y.getY(), y.getWidth(), y.getHeight()};
        System.out.printf("%s", Arrays.toString(toPrint));
        y.repaint();
        y.setVisible(true);
                Canvas.add(y);
        Canvas.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPicture;
    private javax.swing.JButton AddPost;
    private javax.swing.JPanel Canvas;
    private javax.swing.JButton ChangeBack;
    private javax.swing.JPanel MenuBar;
    private javax.swing.JPanel PamplhetCanvas;
    private javax.swing.JTextField SearchField;
    private javax.swing.JLabel SearchLabel;
    private javax.swing.JPanel Testing;
    private javax.swing.JPanel ToolsInHere;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
